#!/usr/bin/env python3
"""Apply selected Wikimedia Commons photos to recipe pages.

- Removes old inline autogenerated SVG illustrations.
- Inserts approved top-of-page photos for a curated subset of recipes.
- Downloads local copies under docs/assets/recipe-photos/.
- Generates docs/image-credits.md for attribution.
"""

from __future__ import annotations

import json
import re
import time
import urllib.parse
import urllib.request
from pathlib import Path
from urllib.error import HTTPError

ROOT = Path(__file__).resolve().parents[1]
RECIPES_DIR = ROOT / "docs" / "recipes"
PHOTOS_DIR = ROOT / "docs" / "assets" / "recipe-photos"
CREDITS_PATH = ROOT / "docs" / "image-credits.md"
IGNORE = {"index.md", "conventions.md", "_template.md"}
PHOTO_START = "<!-- RECIPE_PHOTO_START -->"
PHOTO_END = "<!-- RECIPE_PHOTO_END -->"
UA = "OpenClaw FamilyRecipes Wikimedia Pass/1.0"

SELECTED = {
    "beef-stew-with-green-peas.md": {
        "title": "File:Ragoût viande, petits pois, Tunisie 2018 DSC 7726.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Rago%C3%BBt_viande%2C_petits_pois%2C_Tunisie_2018_DSC_7726.jpg/500px-Rago%C3%BBt_viande%2C_petits_pois%2C_Tunisie_2018_DSC_7726.jpg",
    },
    "black-beluga-lentils-from-le-puy.md": {
        "title": "File:Beluga lentils.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Beluga_lentils.jpg/500px-Beluga_lentils.jpg",
    },
    "black-eyed-peas-salad-cold-dish.md": {
        "title": "File:Black-eyed peas salad (6938556333).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Black-eyed_peas_salad_%286938556333%29.jpg/500px-Black-eyed_peas_salad_%286938556333%29.jpg",
    },
    "blueberry-pancakes-version-2.md": {
        "title": "File:Blueberry pancakes Pj Princeton.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Blueberry_pancakes_Pj_Princeton.jpg/500px-Blueberry_pancakes_Pj_Princeton.jpg",
    },
    "bulgur-pilav.md": {
        "title": "File:Tel sehriyeli bulgur pilav.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Tel_sehriyeli_bulgur_pilav.jpg/500px-Tel_sehriyeli_bulgur_pilav.jpg",
    },
    "butternut-squash-soup.md": {
        "title": "File:Butternut squash soup - El Dorado Kitchen - Nov 2018 - Sarah Stierch 01.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Butternut_squash_soup_-_El_Dorado_Kitchen_-_Nov_2018_-_Sarah_Stierch_01.jpg/500px-Butternut_squash_soup_-_El_Dorado_Kitchen_-_Nov_2018_-_Sarah_Stierch_01.jpg",
    },
    "fennel-salad.md": {
        "title": "File:Fennel and orange salad.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Fennel_and_orange_salad.jpg/500px-Fennel_and_orange_salad.jpg",
    },
    "fried-rice.md": {
        "title": "File:Chinese fried rice homemade.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Chinese_fried_rice_homemade.jpg/500px-Chinese_fried_rice_homemade.jpg",
    },
    "kisir-turkish.md": {
        "title": "File:Kisir (small portion).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Kisir_%28small_portion%29.jpg/500px-Kisir_%28small_portion%29.jpg",
    },
    "menemen.md": {
        "title": "File:Turkish egg dish Menemen.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Turkish_egg_dish_Menemen.jpg/500px-Turkish_egg_dish_Menemen.jpg",
    },
    "oxtail-soup.md": {
        "title": "File:Oxtail soup is repping UT-Austin. -hookemhorns (16054513605).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Oxtail_soup_is_repping_UT-Austin._-hookemhorns_%2816054513605%29.jpg/500px-Oxtail_soup_is_repping_UT-Austin._-hookemhorns_%2816054513605%29.jpg",
    },
    "pancakes.md": {
        "title": "File:Pancakes with fruit.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Pancakes_with_fruit.jpg/500px-Pancakes_with_fruit.jpg",
    },
    "pappardelle-ragu.md": {
        "title": "File:Pappardelle al ragù e piselli.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Pappardelle_al_rag%C3%B9_e_piselli.jpg/500px-Pappardelle_al_rag%C3%B9_e_piselli.jpg",
    },
    "porridge-kids.md": {
        "title": "File:Oatmeal porridge 1-minute with additional ingredients.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Oatmeal_porridge_1-minute_with_additional_ingredients.jpg/500px-Oatmeal_porridge_1-minute_with_additional_ingredients.jpg",
    },
    "potato-salad.md": {
        "title": "File:Potato salad-2.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Potato_salad-2.jpg/500px-Potato_salad-2.jpg",
    },
    "red-lentil-soup.md": {
        "title": "File:Bowl of lentil soup with green and red lentils.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Bowl_of_lentil_soup_with_green_and_red_lentils.jpg/500px-Bowl_of_lentil_soup_with_green_and_red_lentils.jpg",
    },
    "salmon-with-potato-salad.md": {
        "title": "File:Oak-Roasted Salmon With Potato Salad (3119136452).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Oak-Roasted_Salmon_With_Potato_Salad_%283119136452%29.jpg/500px-Oak-Roasted_Salmon_With_Potato_Salad_%283119136452%29.jpg",
    },
    "tarhana-soup.md": {
        "title": "File:Tarhana soup in Ankara.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Tarhana_soup_in_Ankara.jpg/500px-Tarhana_soup_in_Ankara.jpg",
    },
    "turkish-eggplant-salad.md": {
        "title": "File:Patlıcan salata (Eggplant salad).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Patl%C4%B1can_salata_%28Eggplant_salad%29.jpg/500px-Patl%C4%B1can_salata_%28Eggplant_salad%29.jpg",
    },
    "turkish-green-beans-cold-summer-dish.md": {
        "title": "File:How to cook green beans.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/How_to_cook_green_beans.jpg/500px-How_to_cook_green_beans.jpg",
    },
    "vine-leaf-dolma.md": {
        "title": "File:Lebanese Stuffed Grapevine Leaves Waraq 'Inab Dolma Newton Massachusetts.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Lebanese_Stuffed_Grapevine_Leaves_Waraq_%27Inab_Dolma_Newton_Massachusetts.jpg/500px-Lebanese_Stuffed_Grapevine_Leaves_Waraq_%27Inab_Dolma_Newton_Massachusetts.jpg",
    },
    "zucchini-pancakes-mucver.md": {
        "title": "File:Zucchini mint feta pancakes.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Zucchini_mint_feta_pancakes.jpg/500px-Zucchini_mint_feta_pancakes.jpg",
    },
}


def request_json(url: str) -> dict:
    last_error = None
    for attempt in range(6):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.load(resp)
        except HTTPError as e:
            last_error = e
            if e.code != 429:
                raise
            retry_after = e.headers.get("Retry-After")
            delay = float(retry_after) if retry_after else min(30, 2 * (attempt + 1))
            time.sleep(delay)
    raise last_error


def fetch_metadata(file_title: str) -> dict:
    params = {
        "action": "query",
        "format": "json",
        "titles": file_title,
        "prop": "imageinfo",
        "iiprop": "url|extmetadata",
    }
    url = "https://commons.wikimedia.org/w/api.php?" + urllib.parse.urlencode(params)
    data = request_json(url)
    pages = list((data.get("query") or {}).get("pages") or {}).copy()
    pages = list((data.get("query") or {}).get("pages", {}).values())
    if not pages:
        return {}
    ii = (pages[0].get("imageinfo") or [{}])[0]
    meta = ii.get("extmetadata") or {}
    return {
        "description_url": ii.get("descriptionurl"),
        "artist": (meta.get("Artist") or {}).get("value", ""),
        "license": (meta.get("LicenseShortName") or {}).get("value", ""),
        "credit": (meta.get("Credit") or {}).get("value", ""),
    }


def download(url: str, dest: Path) -> None:
    last_error = None
    for attempt in range(6):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as resp:
                dest.write_bytes(resp.read())
            return
        except HTTPError as e:
            last_error = e
            if e.code != 429:
                raise
            retry_after = e.headers.get("Retry-After")
            delay = float(retry_after) if retry_after else min(30, 2 * (attempt + 1))
            time.sleep(delay)
    raise last_error


def clean_body(body: str) -> str:
    body = re.sub(
        rf"\n?{re.escape(PHOTO_START)}.*?{re.escape(PHOTO_END)}\n?",
        "\n",
        body,
        flags=re.S,
    )
    body = re.sub(r"^!\[[^\]]*\]\(\.\./assets/recipes/[^)]+\.svg\)\s*\n?", "", body, flags=re.M)
    return body.lstrip("\n")


def photo_block(rel_path: str, alt: str) -> str:
    return f"{PHOTO_START}\n![{alt}]({rel_path})\n{PHOTO_END}\n\n"


def apply_recipe(path: Path, has_photo: bool) -> None:
    text = path.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---\n"):
        return
    parts = text.split("---\n", 2)
    if len(parts) < 3:
        return
    _, fm, body = parts
    body = clean_body(body)
    block = ""
    if has_photo:
        rel = f"../assets/recipe-photos/{path.stem}.jpg"
        title_match = re.search(r"^title:\s*(.+?)\s*$", fm, re.M)
        alt = title_match.group(1).strip().strip('"') if title_match else path.stem
        block = photo_block(rel, alt)
    path.write_text(f"---\n{fm}---\n\n{block}{body}", encoding="utf-8")


def strip_html(text: str) -> str:
    return re.sub(r"<[^>]+>", "", text or "").strip()


def main() -> int:
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    credits = []

    for path in sorted(RECIPES_DIR.glob("*.md")):
        if path.name in IGNORE:
            continue
        selected = SELECTED.get(path.name)
        if selected:
            dest = PHOTOS_DIR / f"{path.stem}.jpg"
            download(selected["url"], dest)
            time.sleep(1.0)
            meta = fetch_metadata(selected["title"])
            time.sleep(1.0)
            credits.append(
                {
                    "file": path.name,
                    "recipe": path.stem,
                    "commons_title": selected["title"],
                    "artist": strip_html(meta.get("artist")),
                    "license": strip_html(meta.get("license")),
                    "credit": strip_html(meta.get("credit")),
                    "description_url": meta.get("description_url") or f"https://commons.wikimedia.org/wiki/{urllib.parse.quote(selected['title'].replace('File:','File:'), safe=':')}"
                }
            )
            apply_recipe(path, has_photo=True)
        else:
            apply_recipe(path, has_photo=False)

    lines = [
        "# Image Credits",
        "",
        "Recipe photos were selected manually from Wikimedia Commons where a plausible food-photo match existed.",
        "Recipes without a good Commons match were left without a replacement photo for now.",
        "",
        "## Applied recipe photos",
        "",
    ]
    for item in sorted(credits, key=lambda x: x["file"]):
        lines.append(f"- **{item['recipe']}**")
        lines.append(f"  - Commons file: [{item['commons_title']}]({item['description_url']})")
        if item["artist"]:
            lines.append(f"  - Creator: {item['artist']}")
        if item["license"]:
            lines.append(f"  - License: {item['license']}")
        if item["credit"]:
            lines.append(f"  - Credit: {item['credit']}")
    CREDITS_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Applied {len(credits)} recipe photos")
    print(f"Wrote {CREDITS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
